# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

xcodeproj  'PMSIpadUI.xcodeproj'


target 'PMSIpadUI' do

# 网络加载
pod 'Alamofire', '~>3.0'

# json解析
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

# 图片加载
pod 'HanekeSwift'

# 键盘遮挡问题
pod 'IQKeyboardManagerSwift'



#网络检测工具
#pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'

end

